### ISSUE TITLE
A possible bug about pointers

### ISSUE THREAD

**Issue by mangoleaves** [MarcoAttene/Indirect_Predicates#5]
In _implicitPoint3D_LPI::apapExplicit_ in implicit_point.cpp, pointer _d1_ is passed to _getExactLambda_ by value, **not** by reference.

Thus, in _getExactLambda_ and deeper functions, new memory allocation for the passed variable won't change the value of _d1_ in _implicitPoint3D_LPI::apapExplicit_.

In the function _lambda3d_LPI_exact_, lambda_d is also passed by value. If the program allocates new memory to lambda_d in _o.Gen_xxxx_With_PreAlloc_ functions, the new memory address won't be captured by _d1_ in  _implicitPoint3D_LPI::apapExplicit_.

Similar misuses are also found in other places.
They may lead to memory leaks and arithmetic errors.

To fix it, we can pass the pointer to the pointer or the reference to the pointer.

**Comment by MarcoAttene** [comment]
Thank you for your feedback. That is indeed a bug! I am about to upload a major update of the whole library with several improvements and extensions which includes a fix to this. Hope to make it by the end of August

**Comment by MarcoAttene** [comment]
New version just uploaded.
