### ISSUE TITLE
Does it support the running of Webassembly environment ？

### ISSUE THREAD

**Issue by renqh123** [MarcoAttene/Indirect_Predicates#6]
Hello, I have already used this library in a 64 bit X86 architecture project. But now I want to compile it in the webassembly environment, and I seem to be encountering difficulties. Can someone kind-hearted help me?

**Comment by MarcoAttene** [comment]
We have not tried the code on Webassembly and cannot guarantee it works on it. In general, however, please use this channel to report *specific* issues you think should be solved. Generic "difficulties" cannot prompt any response. Thank you for understanding.
